artifacts_root: artifacts

# These are the constants that we are not going to change
data_ingestion:
  root_dir: artifacts/data_ingestion
  push_URL: r'C:\Users\lenovo\Desktop\Emotion-Detection\temp\Emotion.zip'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model.h5
    updated_base_model_path: artifacts/prepare_base_model/base_model.h5


training:
  root_dir: artifacts/training
  model_chkpt: artifacts/training/ResNet50
  trained_model_path: artifacts/training/model.h5

